version: '2'
services:
  curriculi:
    image: kolov/curriculi
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - eureka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/curri
      SPRING_DATA_REDIS_HOST: redis
      LOGGING_LEVEL_ORG_THYMELEAF: trace
  mongodb:
    image: "mongo:3.4.0"
    expose:
      - "27017"
  redis:
    image: redis
    expose:
      - "6379"
  service-docs:
    image: "kolov/service-docs"
    depends_on:
          - mongodb
          - eureka
    environment:
          SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/curri
  eureka:
    image: "netflixoss/eureka:1.3.1"
    expose:
          - "8080"
    ports:
          - "8081:8080"
  config-server:
    image: "kolov/curriculi-config-server"
    ports:
          - "8888:8888"

