spring:
  application:
    name: service-docs

server:
    port: 8502

eureka:
  instance:
      statusPageUrlPath: ${management.context-path}/info
      healthCheckUrlPath: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: "${EUREKA_HOST:http://localhost:8761/eureka/}"
