apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curriculi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: curriculi
    spec:
      containers:
      - name: service-users
        image: localhost:5000/kolov/curriculi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: EUREKA_URL
            value: http://eureka-server:8761/eureka/

