apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curriculi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curriculi
    spec:
      containers:
      - name: service-users
        image: localhost:5000/kolov/curriculi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_HOST
            value: redis
          - name: SPRING_CONFIG_URI
            value: http://config-server:8888
          - name: SERVICE_USERS
            value: service-users:8501
          - name: SERVICE_DOCS
            value: service-users:8502

