apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-users
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
      - name: service-users
        image: localhost:5000/kolov/curriculi-service-users
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
          - name: EUREKA_ENABLED
            value: "true"
