apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
      - name: service-users
        image: localhost:5000/kolov/curriculi-service-users
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
          - name: EUREKA_ENABLED
            value: "true"
          - name: EUREKA_URL
            value: http://eureka-server:8761/eureka/
          - name: MONGODB_URL
            value: mongodb://mongo-users:27017/curri
