apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curriculi-service-users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curriculi-service-users
    spec:
      containers:
      - name: curriculi-service-users
        image: eu.gcr.io/iconic-setup-91510/curriculi-service-users
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
          - name: MONGODB_URL
            value: mongodb://mongo-users:27017/curri-users
