apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
      - name: service-users
        image: 391471456712.dkr.ecr.eu-central-1.amazonaws.com/kolov/curriculi-service-users
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
          - name: MONGODB_URL
            value: mongodb://mongo-users:27017/curri-users
