server:
   port: 8888

# Do NOT define git url/credentials here

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          password: ${GIT_PWD}
          username: ${GIT_USER}