spring:
  application:
    name: service-users
  cloud:
      config:
        enabled: false

server:
    port: 8501

eureka:
#  instance:
#      statusPageUrlPath: ${management.context-path}/info
#      healthCheckUrlPath: ${management.context-path}/health
#  client:
#    serviceUrl:
#      defaultZone: "${EUREKA_HOST:http://localhost:8761/eureka/}"
  enabled: false



ribbon:
  eureka:
     enabled: false

